defaults: &defaults
  organization_domain: 'myorganization.com'
  organization_name: 'MyOrganization'
  short_name_max_length: 40
  url_max_length: 4096
  comments_max_length: 100
  contact_email: 'techsupport@myorganization.com'
  index_view:
    url_max_length: 100
    comments_max_length: 50
  google_oauth2:
    client_id: 'DUMMY_CLIENT_ID'
    client_secret: 'DUMMY_CLIENT_SECRET'


development:
  <<: *defaults

test:
  <<: *defaults
  organization_domain: 'example.org'

production:
  <<: *defaults
